# Generated by Django 4.1.4 on 2022-12-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
