# Generated by Django 4.1.4 on 2022-12-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profileuser_logo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='slug_field',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(default='default_hat.png', null=True, upload_to=''),
        ),
    ]
