# Generated by Django 4.1.4 on 2022-12-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_profileuser_slug_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(blank=True, default='default_hat.png', upload_to='static/main_app/photo/logo'),
        ),
    ]
