# Generated by Django 4.1.4 on 2022-12-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profileuser_logo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(blank=True, default='default_logo.png', height_field=75, upload_to='static/main_app/photo/logo', width_field=75),
        ),
    ]
