# Generated by Django 4.1.4 on 2022-12-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profileuser_logo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(blank=True, default='default_logo.png', upload_to='static/main_app/photo/logo'),
        ),
    ]
