# Generated by Django 4.1.4 on 2023-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profileuser_logo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('theme_post', models.CharField(max_length=300)),
                ('content_post', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('type_travel', models.CharField(choices=[('Domestic Tourism', 'domestic tourism'), ('Inbound Tourism', 'inbound tourism'), ('Outbound Tourism', 'outbound tourism'), ('Leisure Travel', 'leisure travel')], max_length=30)),
            ],
        ),
    ]
