# Generated by Django 4.1.6 on 2023-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_postusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postusermodel',
            name='image_bg',
            field=models.FileField(null=True, upload_to='static/main_app/bg_post/'),
        ),
    ]
