# Generated by Django 4.0 on 2023-02-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_room_online_delete_message_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(max_length=255)),
                ('message', models.JSONField()),
                ('slug_num', models.CharField(max_length=15)),
            ],
        ),
    ]
