# Generated by Django 4.0 on 2023-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_messagechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechat',
            name='user',
            field=models.JSONField(),
        ),
    ]
