# Generated by Django 4.0 on 2023-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_messagechat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechat',
            name='user',
        ),
        migrations.AddField(
            model_name='messagechat',
            name='user1',
            field=models.CharField(max_length=215, null=True),
        ),
        migrations.AddField(
            model_name='messagechat',
            name='user2',
            field=models.CharField(max_length=215, null=True),
        ),
    ]
