# Generated by Django 4.0 on 2023-02-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_messagechat_user_messagechat_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechat',
            name='user1',
            field=models.CharField(max_length=215),
        ),
        migrations.AlterField(
            model_name='messagechat',
            name='user2',
            field=models.CharField(max_length=215),
        ),
    ]
