# Generated by Django 4.0 on 2023-02-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_messagechat_user1_alter_messagechat_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='user2',
        ),
    ]
