# Generated by Django 4.0 on 2023-02-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_messagechat_user1_remove_messagechat_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageChat',
        ),
    ]
