# Generated by Django 4.0 on 2023-03-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=215)),
                ('user2', models.CharField(max_length=215)),
                ('message', models.JSONField(null=True)),
                ('slug_num', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PostUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('theme_post', models.CharField(max_length=300)),
                ('content_post', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('type_travel', models.CharField(choices=[('Domestic Tourism', 'domestic tourism'), ('Inbound Tourism', 'inbound tourism'), ('Outbound Tourism', 'outbound tourism'), ('Leisure Travel', 'leisure travel')], max_length=30)),
                ('image_bg_d', models.FileField(null=True, upload_to='static/main_app/bg_post/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('logo_user', models.ImageField(blank=True, default='default_logo.png', upload_to='static/main_app/photo/logo')),
            ],
        ),
    ]
