# Generated by Django 4.0 on 2023-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_messagechat_date_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postusermodel',
            name='image_bg_d',
            field=models.FileField(blank=True, default='default_post.jpg', null=True, upload_to='static/main_app/photo/photo_post'),
        ),
    ]
