# Generated by Django 4.0 on 2023-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profileuser_slug_profile_alter_profileuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends', to='main_app.ProfileUser'),
        ),
    ]
