# Generated by Django 4.0 on 2023-03-31 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_profileuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='friends',
        ),
        migrations.CreateModel(
            name='FriendsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='main_app.FriendsUsers')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.profileuser')),
            ],
        ),
    ]
