# Generated by Django 4.0 on 2023-03-31 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_alter_friendsusers_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsusers',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendsusers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='auth.user'),
        ),
    ]
