# Generated by Django 4.0 on 2023-03-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_friendsusers_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsusers',
            name='friends',
        ),
    ]
