# Generated by Django 4.0 on 2023-03-31 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_remove_friendsusers_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsusers',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
