# Generated by Django 3.2 on 2023-04-01 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_friendsusers_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='postusermodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='likes_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
