# Generated by Django 3.2 on 2023-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20230401_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postusermodel',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='likes_post', to='main_app.PostUserModel'),
        ),
    ]
