# Generated by Django 3.2.18 on 2023-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_profileuser_logo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postusermodel',
            name='image_bg_d',
            field=models.FileField(default='media/media/default_posts/default_post.jpg', upload_to='media/posts/'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(blank=True, default='media/media/default_logo/default_logo.png', upload_to='media/main_app/logo'),
        ),
    ]
