# Generated by Django 3.2.18 on 2023-06-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20230619_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postusermodel',
            name='image_bg_d',
            field=models.FileField(blank=True, null=True, upload_to='media/posts/'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='logo_user',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo'),
        ),
    ]
